# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b909f7376a6a12fb1d1a5c947a7a7f07e5e999ebce7e9573c1cdc87e1ae808015f5b75be94c0db159c34184319396bf184250fa69739058d95b6c65657728261

test:
  secret_key_base: 56b5408d7aceef1ad2e89a2bd7c2c54fc11fdad1112cbfa5f04f50c279b03ddc8cbdb56ab25e20243243faa98f7112953afcbf3b6c043492cd52403fa929e965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
